version: "3.9"

services:
  hello-world-app:
    build: .
    expose:
      - "8000"
  nginx:
    build:  
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
  db:
    build:
      context: .
      dockerfile: Dockerfile.mariadb
    expose:
      - "3306"